//! `bullang editor-setup` — writes LSP configuration for detected editors.

pub fn cmd_editor_setup() {
    use std::io::Write;
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".to_string());
    let mut configured = 0usize;
    let mut skipped    = 0usize;

    println!("bullang editor-setup");
    println!();

    // ── Neovim ───────────────────────────────────────────────────────────────
    let nvim_dir = std::path::PathBuf::from(&home).join(".config").join("nvim");
    if nvim_dir.exists() {
        let ftdetect = nvim_dir.join("after").join("ftdetect");
        std::fs::create_dir_all(&ftdetect).ok();
        let ftfile = ftdetect.join("bullang.vim");
        if !ftfile.exists() {
            let _ = std::fs::write(&ftfile,
                "au BufRead,BufNewFile *.bu set filetype=bullang\n");
            println!("  [Neovim] wrote {}", ftfile.display());
            configured += 1;
        } else {
            println!("  [Neovim] {} exists \u{2014} skipped", ftfile.display());
            skipped += 1;
        }

        let plugin_dir = nvim_dir.join("after").join("plugin");
        std::fs::create_dir_all(&plugin_dir).ok();
        let lua_file = plugin_dir.join("bullang.lua");
        if !lua_file.exists() {
            let lines: &[&str] = &[
                "-- Bullang LSP (auto-generated by `bullang editor-setup`)",
                r#"local ok, lspconfig = pcall(require, "lspconfig")"#,
                "if not ok then return end",
                r#"local configs = require("lspconfig.configs")"#,
                "if not configs.bullang then",
                "  configs.bullang = {",
                "    default_config = {",
                r#"      cmd = { "bullang", "lsp" },"#,
                r#"      filetypes = { "bullang" },"#,
                r#"      root_dir = lspconfig.util.root_pattern("inventory.bu"),"#,
                "    },",
                "  }",
                "end",
                "lspconfig.bullang.setup({})",
                "",
            ];
            let lua = lines.join("\n");
            let _ = std::fs::write(&lua_file, lua);
            println!("  [Neovim] wrote {}", lua_file.display());
            println!("           (requires nvim-lspconfig)");
            configured += 1;
        } else {
            println!("  [Neovim] {} exists \u{2014} skipped", lua_file.display());
            skipped += 1;
        }
    } else {
        println!("  [Neovim] not detected (~/.config/nvim not found)");
    }
    println!();

    // ── Helix ────────────────────────────────────────────────────────────────
    let helix_dir = std::path::PathBuf::from(&home).join(".config").join("helix");
    if helix_dir.exists() {
        let lang_file = helix_dir.join("languages.toml");
        let existing  = std::fs::read_to_string(&lang_file).unwrap_or_default();
        if existing.contains(r#"name = "bullang""#) {
            println!("  [Helix] bullang already in languages.toml \u{2014} skipped");
            skipped += 1;
        } else {
            let lines: &[&str] = &[
                "",
                "[[language]]",
                r#"name = "bullang""#,
                r#"scope = "source.bullang""#,
                r#"file-types = ["bu"]"#,
                r#"comment-token = "//""#,
                r#"language-servers = ["bullang-lsp"]"#,
                "",
                "[language-server.bullang-lsp]",
                r#"command = "bullang""#,
                r#"args = ["lsp"]"#,
                "",
            ];
            let entry = lines.join("\n");
            let mut f = std::fs::OpenOptions::new()
                .create(true).append(true).open(&lang_file)
                .expect("cannot open languages.toml");
            let _ = f.write_all(entry.as_bytes());
            println!("  [Helix] appended to {}", lang_file.display());
            configured += 1;
        }
    } else {
        println!("  [Helix] not detected (~/.config/helix not found)");
    }
    println!();

    // ── Emacs (eglot) ────────────────────────────────────────────────────────
    let emacs_dir = std::path::PathBuf::from(&home).join(".emacs.d");
    if emacs_dir.exists() {
        let el_file = emacs_dir.join("bullang-lsp.el");
        if !el_file.exists() {
            let lines: &[&str] = &[
                ";; Bullang LSP (auto-generated by `bullang editor-setup`)",
                r#";; Add to init.el: (load (expand-file-name "bullang-lsp.el" user-emacs-directory))"#,
                "(require 'eglot)",
                r#"(add-to-list 'auto-mode-alist '("\\.bu\\'" . prog-mode))"#,
                "(add-to-list 'eglot-server-programs",
                r#"             '(prog-mode . ("bullang" "lsp")))"#,
                "(add-hook 'prog-mode-hook",
                "          (lambda ()",
                "            (when (and buffer-file-name",
                r#"                       (string-suffix-p ".bu" buffer-file-name))"#,
                "              (eglot-ensure))))",
                "",
            ];
            let el = lines.join("\n");
            let _ = std::fs::write(&el_file, el);
            println!("  [Emacs] wrote {}", el_file.display());
            println!(r#"          add to init.el: (load (expand-file-name "bullang-lsp.el" user-emacs-directory))"#);
            configured += 1;
        } else {
            println!("  [Emacs] {} exists \u{2014} skipped", el_file.display());
            skipped += 1;
        }
    } else {
        println!("  [Emacs] not detected (~/.emacs.d not found)");
    }
    println!();

    // ── VS Code ───────────────────────────────────────────────────────────────
    println!("  [VS Code] install the extension (.vsix) from:");
    println!("            https://github.com/My-sidequests/Bullang/releases");
    println!();
    println!("configured: {}   skipped (already set up): {}", configured, skipped);
}
