//! Blueprint-based project init: parsing a `.bu` blueprint file and emitting
//! the corresponding folder tree.

use std::path::{Path, PathBuf};
use std::fs;
use crate::ast::Rank;
use super::{rank_for_depth, write_file};

// ── README written into every blueprint project ───────────────────────────────

pub const BULLANG_README: &str = "# Bullang

Bullang is a structured functional language that transpiles to Rust, Python, C, C++, and Go.
Every project is a hierarchy of folders. Each folder has a rank. Source files live only at
the leaf rank (skirmish). This file was generated by `bullang init --blueprint`.

---

## Hierarchy

Ranks from highest to lowest:

```
war > theater > battle > strategy > tactic > skirmish
```

Each folder must contain an `inventory.bu` declaring its rank.  \
Skirmish folders hold source files. All other ranks hold sub-folders.

Limits per level: 5 sub-folders · 5 source files · 5 functions per file · 5 bullets per function.

---

## Writing a function

Every source file contains only function declarations — no imports, no metadata.

```
let add(a: i32, b: i32) -> result: i32 {
    (a, b) : a + b -> {result};
}
```

`let name(params) -> output_name: ReturnType { body }`

A bullet (pipe statement): `(inputs) : expression -> {binding};`

Rules:
- Every binding must be consumed by a later bullet, except the final output.
- The last bullet must bind to the declared output name.
- No binding may be assigned twice.
- Maximum 5 bullets per function.

---

## Inventory files

Every folder must have `inventory.bu`:

```
#rank: skirmish;
#lang: rs;           ← optional: default convert target
#lib: stdio.h;       ← optional: C/C++ header include (repeatable)

math    : add, subtract, multiply;
helpers : clamp, abs_val;
```

Rules:
- Every .bu source file in the folder must be listed.
- Every function in a file must be listed next to its filename.
- `main.bu` and `blueprint.bu` are reserved — never list them.

---

## Native escape blocks

For logic Bullang pipes cannot express:

```
let sum_vec(values: Vec[i32]) -> result: i32 {
    @rust
    values.iter().sum()
    @end
}
```

Backends: `@rust`  `@python`  `@c`  `@cpp`  `@go`

---

## Builtin standard library

```
let upper(s: String) -> result: String {
    builtin::to_upper
}
```

Universal builtins (work in all 5 backends):

| Category | Builtins |
|----------|----------|
| Math | `abs` `pow` `powf` `sqrt` `clamp` |
| String | `to_upper` `to_lower` `trim` `starts_with` `ends_with` `replace_str` `to_string` `parse_i64` |

Run `bullang stdlib --list` for full signatures and parameter counts.

---

## Types

| Bullang | Description |
|---------|-------------|
| `Vec[T]` | Dynamic array |
| `Option[T]` | Nullable value |
| `Tuple[T, U]` | Fixed-size tuple |
| `Fn[T -> U]` | Function reference |
| `i32`, `i64`, `f64`... | Numeric primitives |
| `bool`, `char`, `String` | Other primitives |

---

## Commands

```
bullang check                validate from anywhere in the tree
bullang convert my_project   transpile (reads #lang, defaults to Rust)
bullang convert file.bu      transpile a single file to stdout
bullang init --help          all init options
bullang stdlib --list        available builtins
bullang lsp                  start the language server
bullang editor-setup         write LSP config for Neovim / Helix / Emacs
bullang update               pull and rebuild from the repository
bullang update --experimental pull and rebuild from the experimental branch
```
";

// ── Blueprint node ────────────────────────────────────────────────────────────

#[derive(Debug)]
pub enum BlueprintNode {
    /// A sub-folder. `lang` is `Some("py")` etc. when written as `python: folder_name {`
    Folder { name: String, lang: Option<String>, children: Vec<BlueprintNode> },
    Entry  { file: String, functions: Vec<String> },
}

// ── Parser ────────────────────────────────────────────────────────────────────

/// Parse a blueprint.bu file into a list of top-level nodes.
pub fn parse_blueprint(source: &str) -> Result<Vec<BlueprintNode>, String> {
    let lines: Vec<&str> = source.lines().collect();
    let indent_unit = detect_indent_unit(&lines);
    parse_block(&lines, 0, 0, indent_unit).map(|(nodes, _)| nodes)
}

fn detect_indent_unit(lines: &[&str]) -> usize {
    for line in lines {
        if line.trim().is_empty() || line.trim_start().starts_with("//") { continue; }
        let spaces = line.len() - line.trim_start().len();
        if spaces > 0 { return spaces; }
    }
    4 // default
}

/// Recursively parse a block of lines at `base_indent` depth.
/// Returns (nodes, index of next unprocessed line).
fn parse_block(
    lines:       &[&str],
    start:       usize,
    base_indent: usize,
    unit:        usize,
) -> Result<(Vec<BlueprintNode>, usize), String> {
    let mut nodes = Vec::new();
    let mut i     = start;

    while i < lines.len() {
        let line    = lines[i];
        let trimmed = line.trim();

        if trimmed.is_empty() || trimmed.starts_with("//") { i += 1; continue; }

        let indent = line.len() - line.trim_start().len();

        if indent < base_indent { break; }

        if indent > base_indent {
            return Err(format!(
                "line {}: unexpected indentation (expected {} spaces, got {}): '{}'",
                i + 1, base_indent, indent, trimmed
            ));
        }

        if trimmed.ends_with('{') || trimmed.ends_with(": {") || {
            // Folder line: either "name {" or "lang: name {" or "name:"
            trimmed.ends_with('{') || trimmed.ends_with(':')
        } {
            // Detect language prefix: "python: folder_name" or just "folder_name"
            // A folder line ends with `{` (block open) or `:` (old indentation style)
            let (lang, folder_name) = parse_folder_header(trimmed);
            if folder_name.is_empty() {
                return Err(format!("line {}: empty folder name", i + 1));
            }
            i += 1;
            let (children, next) = parse_block(lines, i, base_indent + unit, unit)?;
            nodes.push(BlueprintNode::Folder { name: folder_name, lang, children });
            i = next;
        } else {
            let entry = trimmed.trim_end_matches(';');
            if let Some(colon) = entry.find(':') {
                let file = entry[..colon].trim().to_string();
                let fns_str = entry[colon+1..].trim();
                let functions: Vec<String> = fns_str
                    .split(',')
                    .map(|s| s.trim().to_string())
                    .filter(|s| !s.is_empty())
                    .collect();
                if file.is_empty() {
                    return Err(format!("line {}: empty file name in entry", i + 1));
                }
                nodes.push(BlueprintNode::Entry { file, functions });
            } else {
                return Err(format!(
                    "line {}: expected 'folder:' or 'filename: fn1, fn2' — got '{}'",
                    i + 1, trimmed
                ));
            }
            i += 1;
        }
    }

    Ok((nodes, i))
}

/// Parse a folder header line into (Option<lang_ext>, folder_name).
///
/// Accepts these forms:
///   `python: my_folder`   → (Some("py"), "my_folder")
///   `rs: my_folder`       → (Some("rs"), "my_folder")
///   `my_folder`           → (None, "my_folder")
///
/// The folder name part has any trailing `:` or `{` stripped.
fn parse_folder_header(trimmed: &str) -> (Option<String>, String) {
    // Strip trailing `:` or `{`
    let stripped = trimmed.trim_end_matches('{').trim().trim_end_matches(':').trim();

    // Known language names (long form and short form)
    const LANGS: &[(&str, &str)] = &[
        ("rust",   "rs"),
        ("rs",     "rs"),
        ("python", "py"),
        ("py",     "py"),
        ("c",      "c"),
        ("cpp",    "cpp"),
        ("c++",    "cpp"),
        ("go",     "go"),
        ("golang", "go"),
    ];

    // Check if it matches "lang: folder_name"
    if let Some(colon) = stripped.find(':') {
        let prefix = stripped[..colon].trim().to_lowercase();
        let rest   = stripped[colon+1..].trim().to_string();
        if !rest.is_empty() {
            for (long, short) in LANGS {
                if prefix == *long {
                    return (Some(short.to_string()), rest);
                }
            }
        }
    }

    // No language prefix
    (None, stripped.to_string())
}

// ── Blueprint → folder tree ───────────────────────────────────────────────────

pub struct BlueprintResult {
    pub root:          PathBuf,
    pub files_created: Vec<PathBuf>,
}

/// Scaffold a project from a parsed blueprint.
pub fn init_from_blueprint(
    parent:        &Path,
    name:          &str,
    nodes:         &[BlueprintNode],
    lang:          Option<&str>,
    blueprint_src: &str,
) -> Result<BlueprintResult, String> {
    let root = parent.join(name);
    if root.exists() {
        return Err(format!("'{}' already exists.", root.display()));
    }
    fs::create_dir_all(&root)
        .map_err(|e| format!("Could not create '{}': {}", root.display(), e))?;

    let mut files_created: Vec<PathBuf> = Vec::new();

    let max_depth = tree_depth(nodes);
    let root_rank = rank_for_depth(max_depth as u8)
        .ok_or_else(|| "Blueprint tree is too deep (max 6 levels)".to_string())?;

    // Write root inventory.bu
    let mut root_inv = format!("#rank: {};\n", root_rank.name());
    if let Some(l) = lang {
        root_inv.push_str(&format!("\n#lang: {};\n", l));
    }
    let root_entries: Vec<&BlueprintNode> = nodes.iter()
        .filter(|n| matches!(n, BlueprintNode::Entry { .. }))
        .collect();
    if !root_entries.is_empty() {
        root_inv.push('\n');
        for e in root_entries {
            if let BlueprintNode::Entry { file, functions } = e {
                root_inv.push_str(&format!("{}: {};\n", file, functions.join(", ")));
            }
        }
    }
    write_file(&root.join("inventory.bu"), &root_inv, &mut files_created)?;

    let child_folders: Vec<&BlueprintNode> = nodes.iter()
        .filter(|n| matches!(n, BlueprintNode::Folder { .. }))
        .collect();
    for node in child_folders {
        if let BlueprintNode::Folder { name: folder_name, lang: folder_lang, children } = node {
            // Folder lang overrides the blueprint-level lang; if neither set, None
            let effective_lang = folder_lang.as_deref().or(lang);
            emit_blueprint_folder(&root, folder_name, children, max_depth - 1, effective_lang, &mut files_created)?;
        }
    }

    // Copy blueprint source and write README
    write_file(&root.join("blueprint.bu"), blueprint_src, &mut files_created)?;
    write_file(&root.join("README.md"), BULLANG_README, &mut files_created)?;

    Ok(BlueprintResult { root, files_created })
}

fn emit_blueprint_folder(
    parent:          &Path,
    name:            &str,
    children:        &[BlueprintNode],
    depth_remaining: usize,
    inherited_lang:  Option<&str>,
    created:         &mut Vec<PathBuf>,
) -> Result<(), String> {
    let dir = parent.join(name);
    fs::create_dir_all(&dir)
        .map_err(|e| format!("Could not create '{}': {}", dir.display(), e))?;

    let rank = rank_for_depth(depth_remaining as u8)
        .ok_or_else(|| format!("Blueprint nesting too deep at '{}'", name))?;

    let mut inv = format!("#rank: {};\n", rank.name());
    if let Some(l) = inherited_lang {
        inv.push_str(&format!("#lang: {};\n", l));
    }

    let entries: Vec<&BlueprintNode> = children.iter()
        .filter(|n| matches!(n, BlueprintNode::Entry { .. }))
        .collect();
    if !entries.is_empty() {
        inv.push('\n');
        for e in entries {
            if let BlueprintNode::Entry { file, functions } = e {
                inv.push_str(&format!("{}: {};\n", file, functions.join(", ")));
            }
        }
    }
    write_file(&dir.join("inventory.bu"), &inv, created)?;

    for child in children {
        if let BlueprintNode::Folder { name: child_name, lang: child_lang, children: grandchildren } = child {
            // Child's explicit lang overrides the inherited one; propagates further down
            let effective = child_lang.as_deref().or(inherited_lang);
            emit_blueprint_folder(&dir, child_name, grandchildren, depth_remaining - 1, effective, created)?;
        }
    }

    Ok(())
}

fn tree_depth(nodes: &[BlueprintNode]) -> usize {
    let mut max = 0usize;
    for node in nodes {
        if let BlueprintNode::Folder { children, .. } = node {
            let child_depth = 1 + tree_depth(children);
            if child_depth > max { max = child_depth; }
        }
    }
    if max == 0 { 1 } else { max }
}

// ── Display ───────────────────────────────────────────────────────────────────

pub fn print_blueprint_tree(result: &BlueprintResult) {
    println!("created: {}", result.root.display());
    println!();
    let root = &result.root;
    for path in &result.files_created {
        let rel       = path.strip_prefix(root).unwrap_or(path);
        let depth     = rel.components().count().saturating_sub(1);
        let indent    = "  ".repeat(depth);
        let file_name = rel.file_name().and_then(|n| n.to_str()).unwrap_or("?");
        if file_name == "inventory.bu" && depth > 0 {
            let folder = rel.parent()
                .and_then(|p| p.file_name()).and_then(|n| n.to_str()).unwrap_or("?");
            println!("  {}{}/", "  ".repeat(depth - 1), folder);
        }
        let label = match file_name {
            "inventory.bu" => format!("{} (inventory)", file_name),
            "blueprint.bu" => format!("{} (blueprint — copied)", file_name),
            _              => file_name.to_string(),
        };
        println!("  {}  {}", indent, label);
    }
}
