//! Go code generation backend.
//!
//! All files land in a single directory. When main.bu is present everything
//! uses `package main`; otherwise they use `package <crate>` as a library.
//!
//! Bullang snake_case names → Go PascalCase (exported). All functions public.
//!
//! Type mapping:
//!   i8/i16/i32/i64 → int8/int16/int32/int64
//!   u8/u16/u32/u64 → uint8/uint16/uint32/uint64
//!   usize/isize    → uint/int
//!   f32/f64        → float32/float64
//!   bool/char      → bool/rune
//!   String/&str    → string
//!   Vec<T>         → []T
//!   (T,U)          → struct{ V0 T; V1 U }
//!   Option<T>      → *T
//!   fn(T)->U       → func(T) U
//!   ()             → (omitted)

use crate::ast::*;

// ── Source file → Go ──────────────────────────────────────────────────────────

pub fn emit_source_go(file: &SourceFile, package: &str) -> String {
    let pkg  = sanitize_go_pkg(package);
    let mut out = String::new();
    out.push_str("// Generated by Bullang\n");
    out.push_str(&format!("package {}\n\n", pkg));

    // Collect imports needed by this file
    let imports = needed_imports(file);
    if !imports.is_empty() {
        out.push_str("import (\n");
        for imp in &imports { out.push_str(&format!("\t\"{}\"\n", imp)); }
        out.push_str(")\n\n");
    }

    for func in &file.bullets {
        out.push_str(&emit_function_go(func));
        out.push('\n');
    }
    out
}

// ── main.bu → main.go ────────────────────────────────────────────────────────

pub fn emit_main_go(file: &SourceFile, _package: &str) -> String {
    let mut out = String::new();
    out.push_str("// Generated by Bullang — entry point\n");
    out.push_str("package main\n\n");

    // Imports needed by main file
    let imports = needed_imports(file);
    // Always include fmt if @go block is present (user likely uses fmt.Println etc.)
    let mut all_imports = imports;
    if !all_imports.contains(&"fmt".to_string()) {
        // Check if any native Go block is present
        let has_native = file.bullets.iter().any(|b| {
            matches!(&b.body, BulletBody::Native { backend: Backend::Go, .. })
        });
        if has_native { all_imports.push("fmt".to_string()); }
    }

    if !all_imports.is_empty() {
        // Deduplicate while preserving order
        let mut seen = std::collections::HashSet::new();
        let unique: Vec<&str> = all_imports.iter()
            .filter(|s| seen.insert(s.as_str()))
            .map(|s| s.as_str()).collect();
        out.push_str("import (\n");
        for imp in unique { out.push_str(&format!("\t\"{}\"\n", imp)); }
        out.push_str(")\n\n");
    }

    for func in &file.bullets {
        if func.name == "main" {
            out.push_str(&emit_main_function_go(func));
        } else {
            out.push_str(&emit_function_go(func));
        }
        out.push('\n');
    }
    out
}

/// Emit go.mod for the module.
pub fn emit_go_mod(module_name: &str) -> String {
    format!("// Generated by Bullang\nmodule {}\n\ngo 1.21\n", module_name)
}

// ── Import detection ──────────────────────────────────────────────────────────

fn needed_imports(file: &SourceFile) -> Vec<String> {
    let mut imports = Vec::new();

    for func in &file.bullets {
        match &func.body {
            BulletBody::Builtin(name) => {
                match name.as_str() {
                    "sqrt" | "powf" | "pow" => { push_unique(&mut imports, "math"); }
                    "parse_i64" => { push_unique(&mut imports, "strconv"); push_unique(&mut imports, "strings"); }
                    "join" | "split_str" | "trim" | "to_upper" | "to_lower"
                    | "starts_with" | "ends_with" | "replace_str" => {
                        push_unique(&mut imports, "strings");
                    }
                    "to_string" => { push_unique(&mut imports, "fmt"); }
                    "sort" | "sort_by" => { push_unique(&mut imports, "sort"); }
                    _ => {}
                }
            }
            BulletBody::Native { backend: Backend::Go, code } => {
                if code.contains("sort.") { push_unique(&mut imports, "sort"); }
                if code.contains("strings.") { push_unique(&mut imports, "strings"); }
                if code.contains("math.") { push_unique(&mut imports, "math"); }
                if code.contains("fmt.") { push_unique(&mut imports, "fmt"); }
                if code.contains("strconv.") { push_unique(&mut imports, "strconv"); }
                if code.contains("os.") { push_unique(&mut imports, "os"); }
                if code.contains("bufio.") { push_unique(&mut imports, "bufio"); }
            }
            _ => {}
        }
    }
    imports.iter().map(|s| s.to_string()).collect()
}

fn push_unique(v: &mut Vec<&'static str>, s: &'static str) {
    if !v.contains(&s) { v.push(s); }
}

// ── Function emitters ─────────────────────────────────────────────────────────

fn emit_function_go(func: &Bullet) -> String {
    let mut out   = String::new();
    let params    = go_param_list(&func.params);
    let ret       = bu_type_to_go(&func.output.ty);
    let go_name   = to_pascal_case(&func.name);

    if ret.is_empty() {
        out.push_str(&format!("func {}({}) {{\n", go_name, params));
    } else {
        out.push_str(&format!("func {}({}) {} {{\n", go_name, params, ret));
    }
    emit_body_go(&mut out, &func.body, &func.params, &func.output);
    out.push_str("}\n");
    out
}

fn emit_main_function_go(func: &Bullet) -> String {
    let mut out = String::new();
    out.push_str("func main() {\n");
    emit_body_go(&mut out, &func.body, &func.params, &func.output);
    out.push_str("}\n");
    out
}

fn emit_body_go(out: &mut String, body: &BulletBody, params: &[Param], output: &OutputDecl) {
    match body {
        BulletBody::Pipes(pipes) => {
            if pipes.is_empty() { return; }
            let last = pipes.len().saturating_sub(1);
            for (i, pipe) in pipes.iter().enumerate() {
                let expr = emit_expr_go(&pipe.expr);
                out.push_str(&format!("\t{} := {}\n", pipe.binding, expr));
                if i == last {
                    let ret = bu_type_to_go(&output.ty);
                    if !ret.is_empty() {
                        out.push_str(&format!("\treturn {}\n", pipe.binding));
                    }
                }
            }
        }
        BulletBody::Native { backend, code } => {
            match backend {
                Backend::Go => {
                    // Strip common leading whitespace
                    let base = code.lines()
                        .filter(|l| !l.trim().is_empty())
                        .map(|l| l.len() - l.trim_start().len())
                        .min().unwrap_or(0);
                    for line in code.lines() {
                        if line.trim().is_empty() { out.push('\n'); }
                        else {
                            let stripped = if line.len() >= base { &line[base..] }
                                           else { line.trim_start() };
                            // Convert tabs or spaces to single tab
                            out.push_str(&format!("\t{}\n", stripped));
                        }
                    }
                }
                other => {
                    out.push_str(&format!(
                        "\t// ERROR: '@{}' cannot be used in a Go build — use '@go'\n",
                        other.escape_keyword()
                    ));
                }
            }
        }
        BulletBody::Builtin(name) => {
            use crate::stdlib;
            match stdlib::emit_builtin(name, params, &Backend::Go) {
                Ok(code) => {
                    let ret = bu_type_to_go(&output.ty);
                    if ret.is_empty() {
                        out.push_str(&format!("\t{}\n", code));
                    } else {
                        // Cast to declared return type — builtins may return int64
                        // while the function declares int32, float32, etc.
                        out.push_str(&format!("\treturn {}({})\n", ret, code));
                    }
                }
                Err(e) => out.push_str(&format!("\t// ERROR: {}\n", e)),
            }
        }
    }
}

// ── Expression emitters ───────────────────────────────────────────────────────

fn emit_expr_go(expr: &Expr) -> String {
    match expr {
        Expr::Atom(a)      => emit_atom_go(a),
        Expr::BinOp(b)     => format!("{} {} {}",
            emit_atom_go(&b.lhs), b.op, emit_atom_go(&b.rhs)),
        Expr::Tuple(exprs) => {
            format!("struct{{ {} }}{{{}}}",
                exprs.iter().enumerate()
                    .map(|(i, _)| format!("V{} interface{{}}", i))
                    .collect::<Vec<_>>().join("; "),
                exprs.iter().map(emit_expr_go).collect::<Vec<_>>().join(", "))
        }
    }
}

fn emit_atom_go(atom: &Atom) -> String {
    match atom {
        Atom::Ident(s)            => s.clone(),
        Atom::Integer(n)          => n.to_string(),
        Atom::Call { name, args } => {
            let go_name  = to_pascal_case(name);
            let args_str = args.iter().map(|a| match a {
                CallArg::Value(s)     => s.clone(),
                CallArg::BulletRef(s) => to_pascal_case(s),
            }).collect::<Vec<_>>().join(", ");
            format!("{}({})", go_name, args_str)
        }
    }
}

// ── Type mapping ──────────────────────────────────────────────────────────────

pub fn bu_type_to_go(ty: &BuType) -> String {
    match ty {
        BuType::Named(s)     => rust_type_to_go(s),
        BuType::Tuple(inner) => {
            let fields = inner.iter().enumerate()
                .map(|(i, t)| format!("V{} {}", i, bu_type_to_go(t)))
                .collect::<Vec<_>>().join("; ");
            format!("struct{{ {} }}", fields)
        }
        BuType::Array(t, n)  => format!("[{}]{}", n, bu_type_to_go(t)),
        BuType::Unknown      => "interface{}".to_string(),
    }
}

fn rust_type_to_go(s: &str) -> String {
    let s: String = s.split_whitespace().collect();
    match s.as_str() {
        "i8"    => "int8".to_string(),
        "i16"   => "int16".to_string(),
        "i32"   => "int32".to_string(),
        "i64"   => "int64".to_string(),
        "i128"  => "int64".to_string(),
        "isize" => "int".to_string(),
        "u8"    => "uint8".to_string(),
        "u16"   => "uint16".to_string(),
        "u32"   => "uint32".to_string(),
        "u64"   => "uint64".to_string(),
        "u128"  => "uint64".to_string(),
        "usize" => "uint".to_string(),
        "f32"   => "float32".to_string(),
        "f64"   => "float64".to_string(),
        "bool"  => "bool".to_string(),
        "char"  => "rune".to_string(),
        "String" | "&str" => "string".to_string(),
        "()"    => String::new(),
        other   => translate_go_generic(other),
    }
}

fn translate_go_generic(s: &str) -> String {
    if s.starts_with("Vec[") && s.ends_with(']') {
        return format!("[]{}", rust_type_to_go(&s[4..s.len()-1]));
    }
    if s.starts_with("Option[") && s.ends_with(']') {
        return format!("*{}", rust_type_to_go(&s[7..s.len()-1]));
    }
    if s.starts_with('&') {
        return format!("*{}", rust_type_to_go(s[1..].trim()));
    }
    if s.starts_with("Fn[") {
        return translate_fn_type_go(s);
    }
    format!("interface{{}}  /* {} */", s)
}

fn translate_fn_type_go(s: &str) -> String {
    // Fn[T, U -> V]  →  func(T, U) V
    let inner = s.trim_start_matches("Fn[").trim_end_matches(']');
    if inner.is_empty() { return "func()".to_string(); }
    if let Some(arrow) = inner.find("->") {
        let params_str = inner[..arrow].trim();
        let ret_str    = inner[arrow+2..].trim();
        let params: Vec<String> = if params_str.is_empty() { vec![] }
            else { params_str.split(',').map(|p| rust_type_to_go(p.trim())).collect() };
        let ret = rust_type_to_go(ret_str);
        if ret.is_empty() { format!("func({})", params.join(", ")) }
        else { format!("func({}) {}", params.join(", "), ret) }
    } else {
        let ret = rust_type_to_go(inner.trim());
        format!("func() {}", ret)
    }
}

// ── Helpers ───────────────────────────────────────────────────────────────────

fn go_param_list(params: &[Param]) -> String {
    params.iter()
        .map(|p| format!("{} {}", p.name, bu_type_to_go(&p.ty)))
        .collect::<Vec<_>>().join(", ")
}

/// Convert snake_case or camelCase to PascalCase for Go export convention.
pub fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut next_upper = true;
    for ch in s.chars() {
        if ch == '_' {
            next_upper = true;
        } else if next_upper {
            result.extend(ch.to_uppercase());
            next_upper = false;
        } else {
            result.push(ch);
        }
    }
    result
}

pub fn sanitize_go_pkg(name: &str) -> String {
    let lower: String = name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c.to_ascii_lowercase() } else { '_' })
        .collect();
    // Remove leading underscores/digits
    lower.trim_matches(|c: char| !c.is_ascii_alphabetic()).to_string()
}
