//! Python code generation backend.
//!
//! Translates Bullang AST → Python source files.
//! Each bullet becomes a Python function.
//! All functions are module-level — Python has no `pub` keyword.

use crate::ast::*;

// ── Source file → Python ──────────────────────────────────────────────────────

pub fn emit_source_py(file: &SourceFile) -> String {
    let mut out = String::new();
    out.push_str("# Generated by Bullang\n");
    out.push_str("from __future__ import annotations\n");
    out.push_str("from typing import Any, Callable, Optional, List, Tuple\n\n");

    for func in &file.bullets {
        out.push_str(&emit_function_py(func));
        out.push('\n');
    }
    out
}

// ── main.bu → __main__.py ─────────────────────────────────────────────────────

pub fn emit_main_py(file: &SourceFile, module_name: &str) -> String {
    let mut out = String::new();
    out.push_str("# Generated by Bullang — entry point\n");
    out.push_str("from __future__ import annotations\n");
    // Use relative import so the package works when run with python3 -m <name>
    out.push_str("from . import *\n\n");

    for func in &file.bullets {
        if func.name == "main" {
            out.push_str(&emit_main_function_py(func));
        } else {
            out.push_str(&emit_function_py(func));
        }
        out.push('\n');
    }

    // Python entry point guard
    out.push_str("if __name__ == \"__main__\":\n");
    out.push_str("    main()\n");
    out
}

// ── Module init file ──────────────────────────────────────────────────────────

pub fn emit_init_py(child_modules: &[String]) -> String {
    let mut out = String::new();
    out.push_str("# Generated by Bullang\n");
    for module in child_modules {
        out.push_str(&format!("from .{} import *\n", module));
    }
    out
}

// ── Function emitters ─────────────────────────────────────────────────────────

fn py_param_name(name: &str) -> &str {
    // Python reserved words that may appear as Bullang param names
    match name {
        "from" => "from_",
        "import" => "import_",
        "class" => "class_",
        "return" => "return_",
        "pass" => "pass_",
        "for" => "for_",
        "while" => "while_",
        "in" => "in_",
        "not" => "not_",
        "and" => "and_",
        "or" => "or_",
        "if" => "if_",
        "else" => "else_",
        "lambda" => "lambda_",
        "with" => "with_",
        "as" => "as_",
        "try" => "try_",
        "except" => "except_",
        "raise" => "raise_",
        "del" => "del_",
        other => other,
    }
}

fn emit_function_py(func: &Bullet) -> String {
    let mut out = String::new();

    let params = func.params.iter()
        .map(|p| format!("{}: {}", py_param_name(&p.name), bu_type_to_python(&p.ty)))
        .collect::<Vec<_>>().join(", ");

    let ret_ty = bu_type_to_python(&func.output.ty);
    out.push_str(&format!("def {}({}) -> {}:\n", func.name, params, ret_ty));

    emit_body_py(&mut out, &func.body, &func.params);
    out
}

fn emit_main_function_py(func: &Bullet) -> String {
    let mut out = String::new();
    out.push_str("def main() -> None:\n");
    emit_body_py(&mut out, &func.body, &func.params);
    out
}

fn emit_body_py(out: &mut String, body: &BulletBody, params: &[Param]) {
    match body {
        BulletBody::Pipes(pipes) => {
            if pipes.is_empty() {
                out.push_str("    pass\n");
                return;
            }
            let last = pipes.len().saturating_sub(1);
            for (i, pipe) in pipes.iter().enumerate() {
                let expr_str = emit_expr_py(&pipe.expr);
                out.push_str(&format!("    {} = {}\n", pipe.binding, expr_str));
                if i == last {
                    out.push_str(&format!("    return {}\n", pipe.binding));
                }
            }
        }
        BulletBody::Native { backend, code } => {
            match backend {
                Backend::Python => {
                    // Normalise indentation: strip common leading whitespace,
                    // then emit each line with exactly 4 spaces of function-body indent.
                    let base_indent = code.lines()
                        .filter(|l| !l.trim().is_empty())
                        .map(|l| l.len() - l.trim_start().len())
                        .min().unwrap_or(0);
                    for line in code.lines() {
                        if line.trim().is_empty() { out.push('\n'); }
                        else {
                            let stripped = if line.len() >= base_indent { &line[base_indent..] } else { line.trim_start() };
                            out.push_str(&format!("    {}\n", stripped));
                        }
                    }
                }
                Backend::Rust | Backend::C | Backend::Cpp | Backend::Go => {
                    let kw = backend.escape_keyword();
                    out.push_str(&format!(
                        "    raise NotImplementedError(\"'@{}' block cannot run in Python — use '@python' instead\")\n",
                        kw
                    ));
                }
                Backend::Unknown(kw) => {
                    out.push_str(&format!(
                        "    raise NotImplementedError(\"'@{}' is not a supported backend\")\n",
                        kw
                    ));
                }
            }
        }
        BulletBody::Builtin(name) => {
            use crate::stdlib;
            match stdlib::emit_builtin(name, params, &Backend::Python) {
                Ok(code) => out.push_str(&format!("    return {}\n", code)),
                Err(e)   => out.push_str(&format!("    raise NotImplementedError(\"{}\")\n", e)),
            }
        }
    }
}

// ── Expression emitters ───────────────────────────────────────────────────────

fn emit_expr_py(expr: &Expr) -> String {
    match expr {
        Expr::Atom(a)      => emit_atom_py(a),
        Expr::BinOp(b)     => format!(
            "{} {} {}", emit_atom_py(&b.lhs), b.op, emit_atom_py(&b.rhs)
        ),
        Expr::Tuple(exprs) => format!(
            "({})", exprs.iter().map(emit_expr_py).collect::<Vec<_>>().join(", ")
        ),
    }
}

fn emit_atom_py(atom: &Atom) -> String {
    match atom {
        Atom::Ident(s)            => s.clone(),
        Atom::Integer(n)          => n.to_string(),
        Atom::Call { name, args } => {
            let args_str = args.iter().map(|a| match a {
                CallArg::Value(s)     => s.clone(),
                CallArg::BulletRef(s) => s.clone(),
            }).collect::<Vec<_>>().join(", ");
            format!("{}({})", name, args_str)
        }
    }
}

// ── Dedent helper ────────────────────────────────────────────────────────────

/// Strip the common leading whitespace from a block of code.
/// This corrects for users writing indented @python blocks to match
/// surrounding Bullang source indentation.
fn dedent(code: &str) -> String {
    let lines: Vec<&str> = code.lines().collect();

    // Find the minimum indentation (ignoring blank lines)
    let min_indent = lines.iter()
        .filter(|l| !l.trim().is_empty())
        .map(|l| l.len() - l.trim_start().len())
        .min()
        .unwrap_or(0);

    lines.iter()
        .map(|l| {
            if l.trim().is_empty() { String::new() }
            else if l.len() >= min_indent { l[min_indent..].to_string() }
            else { l.to_string() }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

// ── Type mapping: Bullang → Python type hints ─────────────────────────────────

pub fn bu_type_to_python(ty: &BuType) -> String {
    match ty {
        BuType::Named(s) => rust_type_to_python(s),
        BuType::Tuple(inner) => format!(
            "Tuple[{}]",
            inner.iter().map(bu_type_to_python).collect::<Vec<_>>().join(", ")
        ),
        BuType::Array(elem, n) => format!("List[{}]  # [T; {}]", bu_type_to_python(elem), n),
        BuType::Unknown        => "Any".to_string(),
    }
}

fn rust_type_to_python(s: &str) -> String {
    // Strip whitespace for normalised matching
    let s = s.split_whitespace().collect::<String>();
    match s.as_str() {
        // Integer types → int
        "i8"|"i16"|"i32"|"i64"|"i128"|"isize"
        |"u8"|"u16"|"u32"|"u64"|"u128"|"usize" => "int".to_string(),
        // Float types → float
        "f32"|"f64" => "float".to_string(),
        // Boolean
        "bool" => "bool".to_string(),
        // String types
        "String"|"&str"|"&\'staticstr" => "str".to_string(),
        // Unit type
        "()" => "None".to_string(),
        // Passthrough with best-effort translation for generics
        other => translate_generic_type(other),
    }
}

fn translate_generic_type(s: &str) -> String {
    if s.starts_with("Vec[") && s.ends_with(']') {
        let inner = &s[4..s.len()-1];
        return format!("List[{}]", rust_type_to_python(inner));
    }
    if s.starts_with("Option[") && s.ends_with(']') {
        let inner = &s[7..s.len()-1];
        return format!("Optional[{}]", rust_type_to_python(inner));
    }
    if s.starts_with("Result<") && s.ends_with('>') {
        // Simplified: just use the Ok type
        let inner = s[7..s.len()-1].split(',').next().unwrap_or("Any");
        return format!("Optional[{}]  # Result type", rust_type_to_python(inner.trim()));
    }
    if s.starts_with("Fn[") {
        // fn(T) -> U → Callable[[T], U]
        return translate_fn_type(s);
    }
    if s.starts_with('(') && s.contains(',') {
        // Tuple literal type
        let inner = &s[1..s.len()-1];
        let parts: Vec<String> = inner.split(',')
            .map(|p| rust_type_to_python(p.trim()))
            .collect();
        return format!("Tuple[{}]", parts.join(", "));
    }
    // Unknown: pass through as-is with a comment
    format!("Any  # {}", s)
}

fn translate_fn_type(s: &str) -> String {
    // Parse Fn[T, U -> V] → Callable[[T, U], V]
    let inner = s.trim_start_matches("Fn[").trim_end_matches(']');
    if inner.is_empty() { return "Callable".to_string(); }
    if let Some(arrow) = inner.find("->") {
        let params_str = inner[..arrow].trim();
        let ret_str    = inner[arrow+2..].trim();
        let params: Vec<String> = if params_str.is_empty() { vec![] }
            else { params_str.split(',').map(|p| rust_type_to_python(p.trim())).collect() };
        let ret = if ret_str.is_empty() { "None".to_string() }
            else { rust_type_to_python(ret_str) };
        format!("Callable[[{}], {}]", params.join(", "), ret)
    } else {
        let ret = rust_type_to_python(inner.trim());
        format!("Callable[[], {}]", ret)
    }
}
