//! README generation: written on `bullang init`, deleted on `bullang convert`.

use std::path::Path;

pub fn write_project_readme(project_root: &Path) {
    let path = project_root.join("README.md");
    match std::fs::write(&path, bullang_readme()) {
        Ok(_)  => println!("  wrote README.md (delete after reading — removed automatically on convert)"),
        Err(e) => eprintln!("warning: could not write README.md: {}", e),
    }
}

pub fn delete_project_readme(project_root: &Path) {
    let path = project_root.join("README.md");
    if path.exists() {
        if let Err(e) = std::fs::remove_file(&path) {
            eprintln!("warning: could not remove README.md: {}", e);
        }
    }
}

pub fn bullang_readme() -> &'static str {
r#"# Bullang — Quick-start README

> This file was generated by `bullang init` and is **automatically deleted** when
> you run `bullang convert`.  Keep it as a reference while you write your project,
> then let the converter clean it up.

---

## What is Bullang?

Bullang (`.bu`) is a structured transpiler language.  You write plain, typed
source files in a military-themed folder hierarchy, and `bullang convert`
produces clean, compilable code in your target language (Rust, Python, C, C++,
or Go).

The idea is simple: **hierarchy first, then code**.  Every folder has a *rank*
that controls what it may contain and how it is compiled.

---

## Folder hierarchy (depth)

| Rank       | Depth | Role                              |
|------------|-------|-----------------------------------|
| `skirmish` | 1     | Leaf module — holds source files  |
| `tactic`   | 2     | Groups several skirmishes         |
| `strategy` | 3     | Groups several tactics            |
| `battle`   | 4     | Groups several strategies         |
| `theater`  | 5     | Groups several battles            |
| `war`      | 6     | Top-level root of a large project |

A folder at depth 2 (`--depth 2`) is a `tactic` folder that contains
`skirmish` sub-folders.  Each folder must contain an `inventory.bu` file.

---

## The inventory file

Every folder has an `inventory.bu` that describes it:

```
#rank: skirmish;
#lang: rs;
#include: utils;

math    : add, subtract;
helpers : clamp, abs_val;
```

Key directives:

| Directive   | Meaning                                              |
|-------------|------------------------------------------------------|
| `#rank:`    | The rank of *this* folder (required)                 |
| `#lang:`    | Target language: `rs` `py` `c` `cpp` `go`            |
| `#lib:`     | C/C++ header to include (repeatable)                 |

Each line after the directives is an inventory entry: `filename: fn1, fn2;`
Every `.bu` source file in the folder must be listed, and every function
in that file must be named.

---

## Source files

A `.bu` source file contains function declarations.  Every function uses
the **pipe** (`bullet`) syntax — a chain of named steps where each step
consumes inputs and produces a binding:

```
// A simple function — one bullet
let add(a: i32, b: i32) -> result: i32 {
    (a, b) : a + b -> {result};
}

// Two bullets: intermediate binding consumed by the next step
let scale_and_add(x: i32, y: i32, factor: i32) -> result: i32 {
    (x, factor) : x * factor -> {scaled};
    (scaled, y) : scaled + y -> {result};
}
```

Pipe syntax: `(inputs) : expression -> {binding};`

Rules:
- Every binding must be consumed by a later bullet, except the final output.
- The last bullet must bind to the declared output name.
- No binding may be assigned twice.
- Maximum 5 bullets per function, 5 functions per file.

---

### Types

| Bullang type    | Maps to (Rust / Python / C)                |
|-----------------|--------------------------------------------|
| `i32`, `i64`    | `i32` / `int` / `int32_t`                  |
| `f64`           | `f64` / `float` / `double`                 |
| `String`        | `String` / `str` / `char *`                |
| `bool`          | `bool` / `bool` / `int`                    |
| `Vec[T]`        | `Vec<T>` / `list` / unsupported            |
| `Option[T]`     | `Option<T>` / `Optional[T]` / unsupported  |
| `Tuple[T, U]`   | `(T, U)` / `tuple` / unsupported           |

---

### Native escape blocks

When you need to drop down to the target language directly, use a native block.
The backend keyword follows `@` and the block ends with `@end`:

```
let sum_vec(values: Vec[i32]) -> result: i32 {
    @rust
    values.iter().sum()
    @end
}
```

```
let greet(name: String) -> result: String {
    @python
    result = f"Hello, {name}!"
    @end
}
```

Supported backends: `@rust`  `@python`  `@c`  `@cpp`  `@go`

Only the block matching the active backend is emitted; all others are ignored.

---

## Standard library (`builtin::`)

Call a builtin by writing its name as the sole statement in a function body.
The function's parameters are forwarded automatically.

```
let absolute(x: i32) -> result: i32 {
    builtin::abs
}

let shout(s: String) -> result: String {
    builtin::to_upper
}
```

Run `bullang stdlib` to see all available builtins with their signatures.

| Category | Builtins |
|----------|----------|
| Math     | `abs` `pow` `powf` `sqrt` `clamp` |
| String   | `to_upper` `to_lower` `trim` `starts_with` `ends_with` `replace_str` `to_string` `parse_i64` |

---

## CLI reference

| Command                                  | What it does                                     |
|------------------------------------------|--------------------------------------------------|
| `bullang init <name>`                    | Scaffold a new project (depth 2 by default)      |
| `bullang init <name> --depth 4`          | Scaffold with a custom hierarchy depth           |
| `bullang init <name> --blueprint f.bu`   | Init from a blueprint file                       |
| `bullang convert <folder>`               | Transpile the project to the declared `#lang`    |
| `bullang convert <folder> -e py`         | Override target language                         |
| `bullang convert file.bu`                | Transpile a single file to stdout                |
| `bullang check`                          | Validate & type-check without converting         |
| `bullang stdlib`                         | List all builtin functions                       |
| `bullang lsp`                            | Start the LSP server (used by editor plugins)    |
| `bullang editor-setup`                   | Write LSP config for Neovim / Helix / Emacs      |
| `bullang update`                         | Pull & reinstall from main branch                |
| `bullang update --experimental`          | Pull & reinstall from experimental branch        |
| `bullang install`                        | Install bullang to `~/.cargo/bin`                |

---

## Blueprint files

A blueprint (`.bu`) describes a complete project structure in one file so you
can share project templates:

```
#lang: rs

war my_project {
    theater engine {
        battle physics {
            strategy dynamics {
                tactic forces {
                    skirmish gravity {}
                }
            }
        }
    }
}
```

Init from a blueprint with:

```sh
bullang init my_project --blueprint blueprint.bu
```

---

## Typical workflow

```sh
# 1. Create a project
bullang init my_project --depth 3 --lang rs

# 2. Edit the generated .bu files in your editor
#    (LSP diagnostics work if you ran `bullang editor-setup`)

# 3. Validate before converting
bullang check

# 4. Transpile — this README is deleted automatically
bullang convert my_project

# 5. Compile / run the output
cd _my_project && cargo build
```

---

*Source: https://github.com/My-sidequests/Bullang*
"#
}
